ROLE_DEVELOPER = "developer"
ROLE_MANAGER = "manager"
ROLE_OPERATOR = "operator"

ROLE_LABELS = {
    ROLE_DEVELOPER: "開發者",
    ROLE_MANAGER: "管理級",
    ROLE_OPERATOR: "操作員",
}

ROLE_OPTIONS = [
    (ROLE_OPERATOR, ROLE_LABELS[ROLE_OPERATOR]),
    (ROLE_MANAGER, ROLE_LABELS[ROLE_MANAGER]),
    (ROLE_DEVELOPER, ROLE_LABELS[ROLE_DEVELOPER]),
]

DEFAULT_ROLE_PASSWORDS = {
    ROLE_DEVELOPER: "0000",
    ROLE_MANAGER: "1234",
    ROLE_OPERATOR: "",
}

PERMISSION_OPEN_SETTINGS = "open_settings"
PERMISSION_MANAGE_MODELS = "manage_models"
PERMISSION_EXPORT_RECORDS = "export_records"
PERMISSION_VIEW_ALL_RECORDS = "view_all_records"
PERMISSION_VIEW_SESSIONS = "view_sessions"
PERMISSION_USE_SIMULATION = "use_simulation"

ROLE_PERMISSIONS = {
    ROLE_DEVELOPER: {
        PERMISSION_OPEN_SETTINGS,
        PERMISSION_MANAGE_MODELS,
        PERMISSION_EXPORT_RECORDS,
        PERMISSION_VIEW_ALL_RECORDS,
        PERMISSION_VIEW_SESSIONS,
        PERMISSION_USE_SIMULATION,
    },
    ROLE_MANAGER: {
        PERMISSION_OPEN_SETTINGS,
        PERMISSION_EXPORT_RECORDS,
        PERMISSION_VIEW_ALL_RECORDS,
        PERMISSION_VIEW_SESSIONS,
        PERMISSION_USE_SIMULATION,
    },
    ROLE_OPERATOR: set(),
}


def role_label(role):
    return ROLE_LABELS.get(role, ROLE_LABELS[ROLE_OPERATOR])


def has_permission(role, permission):
    return permission in ROLE_PERMISSIONS.get(role, set())


def default_role_passwords():
    return dict(DEFAULT_ROLE_PASSWORDS)
